---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "freshrss.name-webserver" . }}-conf
  labels:
    {{- include "freshrss.labels-webserver" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 8080;
      server_name _;
      root /app/p/;
      index index.php index.html index.htm;
      location ~ ^.+?\.php(/.*)?$ {
        fastcgi_pass {{ include "freshrss.name-app" . }}:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # By default, the variable PATH_INFO is not set under PHP-FPM
        # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
        # NOTE: the separate $path_info variable is required. For more details, see:
        # https://trac.nginx.org/nginx/ticket/321
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
      location / {
        try_files $uri $uri/ index.php;
      }
    }