---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "freshrss.name-webserver" . }}
  labels:
    {{- include "freshrss.labels-webserver" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "freshrss.selectorLabels-webserver" . | nindent 4 }}
