---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.name-app" . }}-data
  labels:
    {{- include "freshrss.labels-app" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.freshrss.storage.data.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.freshrss.storage.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freshrss.name-app" . }}-extensions
  labels:
    {{- include "freshrss.labels-app" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.freshrss.storage.extensions.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.freshrss.storage.extensions.size }}